export const GO_TO_MAIN = "GO_TO_MAIN";
export const GO_TO_SETTINGS = "GO_TO_SETTINGS";
export const PROXY_STATUS_CHANGED = "PROXY_STATUS_CHANGED";
export const SETTINGS_ADDRESS_CHANGED = "SETTINGS_ADDRESS_CHANGED";
export const SETTINGS_PORT_CHANGED = "SETTINGS_PORT_CHANGED";
export const SETTINGS_SAVED = "SETTINGS_SAVED";